databases:
  - name: tronc-system
    databaseName: tronc-system
    user: unlimitedFinite

services:
  - type: web
    name: tronc-system
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tronc-system
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false